import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Onest } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//  Load Onest font with specific weights
const onest = Onest({
  subsets: ["latin"], // Optimize for Latin characters
  weight: ["300", "400", "500", "600", "700", "800"], // Choose needed weights
  display: "swap", // Prevent layout shifts
  variable: "--font-onest", // Custom CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
